<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>Phalcon</title>
		<?php use Phalcon\Tag; ?>
		<?php echo Tag::stylesheetLink("public/css/bootstrap.css"); ?>

<div class="container">
<h2>Sign using this form</h2>

<?php 
#controller/imeActiona u controlleru
echo Tag::form("upis/unos"); 
?>

 <p>
    <label for="ime">Ime</label>
    <?php echo Tag::textField("ime") ?>
 </p>

 <p>
    <label for="prezime">Prezime</label>
    <?php echo Tag::textField("prezime") ?>
 </p>

 <p>
    <label for="mreza">Mreža</label>
    <?php echo Tag::selectStatic("mreza", array("091" => "091", "092" => "092", "095" => "095", "097" => "097", "098" => "098", "099" => "099")) ?>
 </p>
 
 <p>
    <label for="broj">Broj</label>
    <?php echo Tag::textField("broj") ?>
 </p>

 <p>
    <?php echo Tag::submitButton("Prijavi se") ?>
 </p>

</form>
</div>
	</body>
</html>